apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: bert-large-fp32-training
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          serviceAccountName: model-service
          containers:
          - name: mpi-launcher
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-large-fp32-training
            imagePullPolicy: Always
            workingDir: /
            command:
            - $(MODEL_DIR)/examples/fp32_training_multi_node.sh
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: /Users
          volumes:
          - name: datasets
            persistentVolumeClaim:
              claimName: datasets-pvc
          - name: users
            persistentVolumeClaim:
              claimName: users-pvc
    Worker:
      replicas: 2
      template:
        spec:
          serviceAccountName: model-service
          containers:
          - name: mpi-worker
            image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-large-fp32-training
            imagePullPolicy: Always
            workingDir: /
            volumeMounts:
            - name: datasets
              mountPath: $(DATASET_DIR)
              readOnly: true
            - name: users
              mountPath: /Users
          volumes:
          - name: datasets
            persistentVolumeClaim:
              claimName: datasets-pvc
          - name: users
            persistentVolumeClaim:
              claimName: users-pvc
