apiVersion: v1
kind: Pod
metadata:
  name: bert-large-fp32-training
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-fp32-training
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mlops-env
    workingDir: /
    command:
    - $(MODEL_DIR)/examples/fp32_training_single_node.sh
