apiVersion: v1
kind: Pod
metadata:
  name: bert-large-fp32-training
spec:
  serviceAccountName: model-service
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-language-modeling-bert-large-fp32-training
    imagePullPolicy: Always
    command:
    - $(MODEL_DIR)/bert-large-fp32-training/examples/fp32_training_single_node.sh
    volumeMounts:
    - name: datasets
      mountPath: $(DATASET_DIR)
      readOnly: true
    - name: users
      mountPath: /Users
  volumes:
  - name: users
    persistentVolumeClaim:
      claimName: users-pvc
  - name: datasets
    persistentVolumeClaim:
      claimName: datasets-pvc
