apiVersion: v1
kind: Pod
metadata:
  name: resnet50v1-5-fp32-training
spec:
  securityContext:
    runAsUser: 11486040
    runAsGroup: 17685
    fsGroup: 17685
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mlops-env
    workingDir: /
    command:
    - $(MODEL_DIR)/examples/fp32_training_multi_node.sh
