apiVersion: v1
kind: Pod
metadata:
  name: resnet50v1-5-fp32-training
spec:
  serviceAccountName: model-service
  containers:
  - name: single-node
    image: $(REGISTRY)/model-zoo:2.1.0-image-recognition-resnet50v1-5-fp32-training
    imagePullPolicy: Always
    command:
    - $(MODEL_DIR)/examples/tensorflow/resnet50v1_5/fp32_training_full.sh
    volumeMounts:
    - name: datasets
      mountPath: $(DATASET_DIR)
      readOnly: true
    - name: users
      mountPath: /Users
  volumes:
  - name: users
    persistentVolumeClaim:
      claimName: users-pvc
  - name: datasets
    persistentVolumeClaim:
      claimName: datasets-pvc
